# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: space_telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'space_telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15space_telemetry.proto\x12\x0fspace_telemetry\"\x98\x02\n\rTelemetryData\x12\x15\n\rspacecraft_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x12\n\nposition_x\x18\x03 \x01(\x01\x12\x12\n\nposition_y\x18\x04 \x01(\x01\x12\x12\n\nposition_z\x18\x05 \x01(\x01\x12\x12\n\nvelocity_x\x18\x06 \x01(\x01\x12\x12\n\nvelocity_y\x18\x07 \x01(\x01\x12\x12\n\nvelocity_z\x18\x08 \x01(\x01\x12\x13\n\x0btemperature\x18\t \x01(\x01\x12\x17\n\x0fradiation_level\x18\n \x01(\x01\x12\x14\n\x0c\x65nergy_level\x18\x0b \x01(\x01\x12\x0c\n\x04mode\x18\x0c \x01(\t\x12\x13\n\x0b\x61lert_level\x18\r \x01(\t\"\xba\x01\n\x07\x43ommand\x12\x15\n\rspacecraft_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ommand_type\x18\x02 \x01(\t\x12<\n\nparameters\x18\x03 \x03(\x0b\x32(.space_telemetry.Command.ParametersEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"`\n\x11TelemetryResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12*\n\x08\x63ommands\x18\x03 \x03(\x0b\x32\x18.space_telemetry.Command2i\n\x10TelemetryService\x12U\n\rSendTelemetry\x12\x1e.space_telemetry.TelemetryData\x1a\".space_telemetry.TelemetryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'space_telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_PARAMETERSENTRY']._loaded_options = None
  _globals['_COMMAND_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_TELEMETRYDATA']._serialized_start=43
  _globals['_TELEMETRYDATA']._serialized_end=323
  _globals['_COMMAND']._serialized_start=326
  _globals['_COMMAND']._serialized_end=512
  _globals['_COMMAND_PARAMETERSENTRY']._serialized_start=463
  _globals['_COMMAND_PARAMETERSENTRY']._serialized_end=512
  _globals['_TELEMETRYRESPONSE']._serialized_start=514
  _globals['_TELEMETRYRESPONSE']._serialized_end=610
  _globals['_TELEMETRYSERVICE']._serialized_start=612
  _globals['_TELEMETRYSERVICE']._serialized_end=717
# @@protoc_insertion_point(module_scope)
