# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: space_telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'space_telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15space_telemetry.proto\x12\ttelemetry\"\xe0\x04\n\rTelemetryData\x12\x15\n\rspacecraft_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x12\n\nposition_x\x18\x03 \x01(\x01\x12\x12\n\nposition_y\x18\x04 \x01(\x01\x12\x12\n\nposition_z\x18\x05 \x01(\x01\x12\x12\n\nvelocity_x\x18\x06 \x01(\x01\x12\x12\n\nvelocity_y\x18\x07 \x01(\x01\x12\x12\n\nvelocity_z\x18\x08 \x01(\x01\x12\x13\n\x0btemperature\x18\t \x01(\x01\x12\x15\n\ranomaly_count\x18\n \x01(\x05\x12\x18\n\x10\x61nomaly_severity\x18\x0b \x01(\t\x12\x1c\n\x14\x61nomaly_descriptions\x18\x0c \x01(\t\x12\x16\n\x0e\x64\x65\x63isions_made\x18\r \x01(\x05\x12\x1e\n\x16\x64\x65\x63isions_descriptions\x18\x0e \x01(\t\x12\x14\n\x0csos_required\x18\x0f \x01(\x08\x12\x12\n\nsos_reason\x18\x10 \x01(\t\x12\x16\n\x0esignal_quality\x18\x11 \x01(\x01\x12\x14\n\x0csequence_num\x18\x12 \x01(\x05\x12\x18\n\x10\x61nomaly_detected\x18\x13 \x01(\x08\x12\x18\n\x10\x64oppler_shift_hz\x18\x14 \x01(\x01\x12\x17\n\x0f\x63\x61rrier_freq_hz\x18\x15 \x01(\x01\x12\x1d\n\x15\x65rror_correction_type\x18\x16 \x01(\t\x12\x12\n\ndata_bytes\x18\x17 \x01(\x05\x12\x14\n\x0cparity_bytes\x18\x18 \x01(\x05\x12#\n\x1b\x65rror_correction_capability\x18\x19 \x01(\x05\x32Y\n\x10TelemetryService\x12\x45\n\rSendTelemetry\x12\x18.telemetry.TelemetryData\x1a\x18.telemetry.TelemetryData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'space_telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYDATA']._serialized_start=37
  _globals['_TELEMETRYDATA']._serialized_end=645
  _globals['_TELEMETRYSERVICE']._serialized_start=647
  _globals['_TELEMETRYSERVICE']._serialized_end=736
# @@protoc_insertion_point(module_scope)
